---
title: "Resources"
description: |
  Bayesian Course Websites and Syllabi at the Undergraduate Level

---


## Courses
 
- Carleton College by [Adam Loy](https://github.com/aloy/math315-fall2019){target="_blank"}

- Duke University by [Alexander Volfovsky](https://www2.stat.duke.edu/courses/Fall18/sta601.001//){target="_blank"}

- University of Iowa by [Kate Cowles](https://stat.uiowa.edu/syllabi-stat4520-22s138-bayesian-statistics){target="_blank"}

- Smith College by [Miles Ott](https://www.dropbox.com/s/bj91cfk4tkfjwmy/SDS%20390%20Bayes%20Fall%202020%20Syllabus.pdf?dl=0){target="_blank"}

- The Ohio State University by [multiple instructors](https://stat.osu.edu/courses/stat-3303#:~:text=Topics%20include%3A%20formulation%20of%20decision,characterizing%20and%20finding%20optimal%20decisions.){target="_blank"}

- University of California Irvine by [Mine Dogucu](https:stats115.com){target="_blank"}  

- University of Pennsylvania by [Shane Jensen](https://apps.wharton.upenn.edu/syllabi/2019A/STAT442001/){target="_blank"}

- Vassar College by [Jingchen Monika Hu](https://github.com/monika76five/Undergrad-Bayesian-Statistics){target="_blank"}



## Editing the List

If you would like to make suggestions to this list, please do so either by creating an issue or a pull request on the [GitHub repo](https://www.github.com/mdogucu/undergrad-bayes){target="_blank"} (prefered) or via email. Please note that this list specifically focuses on _undergraduate_ Bayesian education. If you are making suggestions of a resource, please note how it is appropriate at the _undergraduate level_ if it is not obvious from the title or abstract. 

